# Generated by Django 5.0.6 on 2025-10-31 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citizen_id", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ELIGIBLE", "Eligible"),
                            ("NOT_FOUND", "Citizen Not Found"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exists_in_system", models.BooleanField(default=False)),
                (
                    "citizen_data",
                    models.JSONField(
                        blank=True,
                        help_text="Data returned from external API",
                        null=True,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "external_api_status_code",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Affiliation Check",
                "verbose_name_plural": "Affiliation Checks",
                "db_table": "affiliation_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["citizen_id", "-checked_at"],
                        name="affiliation_citizen_a5315c_idx",
                    ),
                    models.Index(
                        fields=["status", "-checked_at"],
                        name="affiliation_status_b0de2c_idx",
                    ),
                ],
            },
        ),
    ]
