# Generated by Django 5.0.6 on 2025-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationcheck',
            name='status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible for Affiliation'), ('ALREADY_AFFILIATED', 'Already Affiliated'), ('NOT_FOUND', 'Citizen Not Found'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
